name: NorCal Partners Real Estate
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5
title: NorCal Partners Real Estate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005691'
    - '#fefb82'
    - '#75928e'
    - '#47738a'
    - '#bfce84'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
